version: 1.0.{build}
image: Visual Studio 2017

environment:
  matrix:
  - PYTHON: "C:\\Python37-x64"
  - PYTHON: "C:\\Python27"

install:
- '%PYTHON%\python.exe -m pip install -U setuptools wheel'

build_script:
- '%PYTHON%\python.exe -m pip install .[dev,test]'

test_script:
- '%PYTHON%\python.exe -c "import fs.sshfs; print(fs.sshfs.__version__)"'

#after_test:
#- '%PYTHON%\python.exe -m codecov'
