sudo: false
language: python
cache: pip

services:
- docker

python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 'pypy'
- 'pypy-5.3.1'

addons:
  ssh_known_hosts:
  - localhost

matrix:
  allow_failures:
  - python: 'pypy'
  - python: 'pypy-5.3.1'

before_install:
- docker pull sjourdan/alpine-sshd
- pip install -r tests/requirements.txt -U

install:
# Use Python 3.6 inplace to get coverage data
- if [[ $TRAVIS_PYTHON_VERSION != 3.6 ]]; then pip install .; fi
- pip install -U https://github.com/Pyfilesystem/pyfilesystem2/archive/master.zip

script:
- green -rvvkq

after_script:
- codecov

notifications:
  email:
  - althonosdev@gmail.com
