sudo: false
language: python
cache: pip

env:
- FS_SSHFS_USER="user" FS_SSHFS_PASS="pass" FS_SSHFS_PORT=2222

services:
- docker

python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 'pypy'
- 'pypy3'

addons:
  ssh_known_hosts:
  - localhost

matrix:
  allow_failures:
  - python: '2.6'
  - python: '3.2'
  - python: 'pypy'
  - python: 'pypy3'

before_install:
- docker pull atmoz/sftp
- docker run -p ${FS_SSHFS_PORT}:22 -d atmoz/sftp ${FS_SSHFS_USER}:${FS_SSHFS_PASS}:::test

install:
- pip install -r tests/requirements.txt

script:
- green -rvvkq

after_script:
- codecov
