sudo: false
language: python
cache: pip

services:
- docker

python:
- '2.6'
- '2.7'
- '3.2'
- '3.3'
- '3.4'
- '3.5'
- '3.6'
- 'pypy'
- 'pypy3'

addons:
  ssh_known_hosts:
  - localhost

matrix:
  allow_failures:
  - python: '2.6'
  - python: '3.2'
  - python: 'pypy'
  - python: 'pypy3'

before_install:
- docker pull sjourdan/alpine-sshd
- pip install -r tests/requirements.txt
- if [ "$TRAVIS_BRANCH" == "feat-namespace" ]; then
  pip install "https://github.com/althonos/pyfilesystem2/archive/feat-namespace.zip";
  fi

install:
- pip install .

script:
- green -rvvkq

after_script:
- codecov
